// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxzfktuxbvcybmdtzkzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4emZrdHV4YnZjeWJtZHR6a3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDE3NzUsImV4cCI6MjA2NzI3Nzc3NX0.wDw7EZdyLQknWAAy08g9yBmsI4iLSe5ohnoLoogyW4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});